apiVersion: v1
kind: Secret
metadata:
  name: python-health-demo-secret
type: Opaque
stringData:
  # 对应 app.py 中使用的环境变量 HTTPS_CERT_PWD
  # 这里默认值为 "changeit" (对应 generate_certs.sh 的默认值)
  # 如果您生成证书时使用了不同密码，请修改此处
  https-cert-pwd: "changeit"
