apiVersion: v1
kind: Service
metadata:
  name: api-name-spring-samples-svc
  labels:
    app: api-name-spring-samples
spec:
  selector:
    app: api-name-spring-samples
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
  type: ClusterIP